package com.callahanwilliam.contactmanager.model.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.List;

@DynamoDBTable(tableName = "contact_manager")
public class Person {
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	
	private String firstName;
	
	private String lastName;
	
	private String primaryEmail;
	
	private List<String> secondaryEmailList;
	
	private List<Address> addressList;
	
	private List<Phone> phoneList;
	
	public Person() {
	
	}
	
	public String getId() {
		return id;
	}
	
	public void setId(String id) {
		this.id = id;
	}
	
	public String getFirstName() {
		return firstName;
	}
	
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	public String getLastName() {
		return lastName;
	}
	
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	
	public String getPrimaryEmail() {
		return primaryEmail;
	}
	
	public void setPrimaryEmail(String primaryEmail) {
		this.primaryEmail = primaryEmail;
	}
	
	@DynamoDBAttribute(attributeName = "secondary_emails")
	public List<String> getSecondaryEmailList() {
		return secondaryEmailList;
	}
	
	public void setSecondaryEmailList(List<String> secondaryEmailList) {
		this.secondaryEmailList = secondaryEmailList;
	}
	
	@DynamoDBAttribute(attributeName = "addresses")
	public List<Address> getAddressList() {
		return addressList;
	}
	
	public void setAddressList(List<Address> addressList) {
		this.addressList = addressList;
	}
	
	@DynamoDBAttribute(attributeName = "phone_numbers")
	public List<Phone> getPhoneList() {
		return phoneList;
	}
	
	public void setPhoneList(List<Phone> phoneList) {
		this.phoneList = phoneList;
	}
}
