package com.callahanwilliam.contactmanager.model.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.List;
import java.util.Set;

@DynamoDBTable(tableName = "contact_manager")
public class Person {
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	
	private String firstName;
	
	private String lastName;
	
	private String primaryEmail;
	
	private String secondaryEmail;
	
	private Address address;
	
	private List<Phone> phoneList;
	
	public Person() {
	
	}
	
	public String getId() {
		return id;
	}
	
	public void setId(String id) {
		this.id = id;
	}
	
	public String getFirstName() {
		return firstName;
	}
	
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	public String getLastName() {
		return lastName;
	}
	
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	
	public String getPrimaryEmail() {
		return primaryEmail;
	}
	
	public void setPrimaryEmail(String primaryEmail) {
		this.primaryEmail = primaryEmail;
	}
	
	public String getSecondaryEmail() {
		return secondaryEmail;
	}
	
	public void setSecondaryEmail(String secondaryEmail) {
		this.secondaryEmail = secondaryEmail;
	}
	
	@DynamoDBAttribute(attributeName = "address")
	public Address getAddress() {
		return address;
	}
	
	public void setAddress(Address address) {
		this.address = address;
	}
	
	@DynamoDBAttribute(attributeName = "phone_numbers")
	public List<Phone> getPhoneList() {
		return phoneList;
	}
	
	public void setPhoneList(List<Phone> phoneList) {
		this.phoneList = phoneList;
	}
}
